server:
  # please don't modify it if you don't know what you are doing
  port: ${PORT:8080}

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/imoive?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/IMovie
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

#  flyway:
#    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: create # disable DB schema creation from entity
#      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  thymeleaf:
    mode: HTML

