server:
  # please don't modify it if you don't know what you are doing
  port: ${PORT:8082}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iMovie
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  flyway:
#    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update # disable DB schema creation from entity
  thymeleaf:
    mode: HTML
